Done
Signed-off-by: João Pereira <joaod@vmware.com>

diff --git a/.github/workflows/published_release.yml b/.github/workflows/published_release.yml
--- a/.github/workflows/published_release.yml
+++ b/.github/workflows/published_release.yml
@@ -139,7 +139,7 @@ jobs:
           filename="./${{ github.event.client_payload.toolName }}.rb"
           cat $filename
 
-  prepare-install-sh:
+  prepare-releases-file-for-install-sh:
     runs-on: ubuntu-latest
     needs: process-release-information
     steps:
@@ -152,31 +152,68 @@ jobs:
         with:
           name: ytt-data-values-for-release
           path: ./tmp/release.yml
-      - name: Checkout website repository
-        uses: actions/checkout@v2
+      - name: Install ytt
+        uses: vmware-tanzu/carvel-setup-action@v1
         with:
-          persist-credentials: false
-          repository: vmware-tanzu/carvel
-          path: carvel
-          ref: develop
-      - name: generate install.sh
+          only: ytt
+      - name: Generate new releases.yaml
         run: |
-          set -e -x
-          
-          ./scripts/generate_install_sh.sh ${{ github.event.client_payload.toolName }} ./carvel/site/static/install.sh > ./install.sh
-          
-          cat ./install.sh
-      - name: Generate Homebrew File
+          ytt -f ./tmp/release.yml -f releases.yaml -f scripts/releases/overlay.yaml > ./tmp/releases.yml
+          diff ./tmp/releases.yml releases.yml
+          cp ./tmp/releases.yml releases.yml
+      - name: Commit & Push changes
+        env:
+          AUTHOR_NAME: k8slt
+          AUTHOR_EMAIL: klt@groups.vmware.com
+          REPOSITORY: vmware-tanzu/homebrew-carvel
+          BRANCH: develop
+          FORCE: false
+          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
+          GITHUB_DEPLOY_PRIVATE_KEY: ${{ secrets.HOMEBREW_DEPLOY_PRIVATE_KEY }}
         run: |
-          set -e -x
-          curl -L https://carvel.dev/install.sh | bash
-          filename="./${{ github.event.client_payload.toolName }}.rb"
-          
-          ./scripts/generate_homebrew_formula.sh ./tmp/release.yml > $filename
-          
-          cat $filename
-      - name: Upload Homebrew File
-        uses: actions/upload-artifact@v2
-        with:
-          name: homebrew-formula
-          path: ./${{ github.event.client_payload.toolName }}.rb
+          set -e
+  
+          timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
+  
+          AUTHOR_EMAIL=${AUTHOR_EMAIL:-'github-actions[bot]@users.noreply.github.com'}
+          AUTHOR_NAME=${AUTHOR_NAME:-'github-actions[bot]'}
+          MESSAGE=${MESSAGE:-"chore: autopublish ${timestamp}"}
+          FORCE=${FORCE:-false}
+          REPOSITORY=${REPOSITORY:-$GITHUB_REPOSITORY}
+  
+          echo "Push to branch $BRANCH";
+          [ -z "${BRANCH}" ] && {
+            echo 'Missing branch';
+            exit 1;
+          };
+  
+          if [ -z "${GITHUB_TOKEN}" ] && [ -z "${GITHUB_DEPLOY_PRIVATE_KEY}" ]; then
+              echo 'Missing required input "github_token: ${{ secrets.GITHUB_TOKEN }} OR "github_deploy_private_key: ${{ secrets.GITHUB_DEPLOY_PRIVATE_KEY }}".';
+              exit 1;
+          fi
+  
+          if ${FORCE}; then
+              _FORCE_OPTION='--force'
+          fi
+  
+          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${REPOSITORY}.git"
+  
+          if [ -n "${GITHUB_DEPLOY_PRIVATE_KEY}" ]; then
+            remote_repo="git@github.com:${REPOSITORY}"
+  
+            tempkey=`basename $0`
+            TMP_DEPLOY_PRIV_KEY=`mktemp /tmp/${tempkey}.XXXXXX` || exit 1
+            echo "${GITHUB_DEPLOY_PRIVATE_KEY}" > $TMP_DEPLOY_PRIV_KEY
+            eval $(ssh-agent -s)
+            ssh-add ${TMP_DEPLOY_PRIV_KEY}
+          fi
+  
+          git config http.sslVerify true
+          git config --local user.email "${AUTHOR_EMAIL}"
+          git config --local user.name "${AUTHOR_NAME}"
+  
+          git add -A
+  
+          git commit -m "${MESSAGE}" $_EMPTY || exit 0
+  
+          git push "${remote_repo}" HEAD:"${BRANCH}" --follow-tags $_FORCE_OPTION;
